# Generated by Django 5.0.4 on 2024-04-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="new_todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskTitle", models.CharField(max_length=50)),
                ("taskDesc", models.CharField(max_length=500)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo.register"
                    ),
                ),
            ],
            options={"db_table": "todo",},
        ),
    ]
