# Generated by Django 5.0.4 on 2024-04-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="new_todo", table="new_todo",),
    ]
