# Generated by Django 5.0.4 on 2024-04-26 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_new_todo_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_todo",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="todo.register",
            ),
        ),
    ]
