# Generated by Django 5.0.4 on 2024-04-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_new_todo_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="new_todo", name="username",),
    ]
