# Generated by Django 5.0.4 on 2024-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_remove_new_todo_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskTitle", models.CharField(max_length=50)),
                ("taskDesc", models.CharField(max_length=500)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(name="new_todo",),
    ]
