# Generated by Django 5.0.4 on 2024-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_task_delete_new_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
